#!/bin/bash
set -ex

kern="$DPKG_MAINTSCRIPT_PACKAGE"
kver=${kern/linux-image-/}

U_BOOT_PARAMETERS="consoleblank=0 loglevel=7 rw splash plymouth.ignore-serial-consoles vt.global_cursor_default=0" \
/etc/kernel/postinst.d/zz-u-boot-menu $kver

bootpoint=$(df | grep /boot | tail -n1 | awk '{print $1}')
dd if=/boot/u-boot-rockchip.bin of="${bootpoint/[0-9]/}" bs=32k seek=1 conv=fsync
