#!/bin/sh

## live-build(7) - System Build Scripts
## Copyright (C) 2006-2012 Daniel Baumann <daniel@debian.org>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

# Including common functions
( . "${LIVE_BUILD}/scripts/build.sh" > /dev/null 2>&1 || true ) || . /usr/lib/live/build.sh

# Setting static variables
DESCRIPTION="$(Echo 'mount /dev/pts')"
HELP=""
USAGE="${PROGRAM} {install|remove} [--force]"

Arguments "${@}"

# Ensure that a system is built as root
lb testroot

# Reading configuration files
Read_conffiles config/all config/common config/bootstrap config/chroot config/binary config/source
Set_defaults

# Requiring stage file
Require_stagefile .build/config .build/bootstrap

case "${1}" in
	install)
		Echo_message "Begin mounting /dev/pts..."

		# Checking stage file
		Check_stagefile .build/chroot_devpts

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		if [ "${LB_USE_FAKEROOT}" != "true" ]
		then
			# Creating mountpoint
			mkdir -p chroot/dev/pts

			# Mounting /dev/pts
			${LB_ROOT_COMMAND} mount --bind chroot chroot || true
			${LB_ROOT_COMMAND} mount devpts-live -t devpts -o gid=5,mode=620 chroot/dev/pts || true
		fi

		# Creating stage file
		Create_stagefile .build/chroot_devpts
		;;

	remove)
		Echo_message "Begin unmounting /dev/pts..."

		# Checking lock file
		Check_lockfile .lock

		# Creating lock file
		Create_lockfile .lock

		# Unmounting /dev/pts
		if [ "${LB_USE_FAKEROOT}" != "true" ]
		then
			if grep -qs "$(pwd)/chroot/dev/pts" /proc/mounts || Find_files chroot/dev/pts/*
			then
				${LB_ROOT_COMMAND} umount chroot/dev/pts
			else
				${LB_ROOT_COMMAND} umount -f chroot/dev/pts > /dev/null 2>&1 || true
			fi
			if grep -qs "$(pwd)/chroot" /proc/mounts || Find_files chroot/*
			then
				${LB_ROOT_COMMAND} umount chroot/
			else
				${LB_ROOT_COMMAND} umount -f chroot/ > /dev/null 2>&1 || true
			fi
		fi

		# Removing stage file
		rm -f .build/chroot_devpts
		;;

	*)
		Usage
		;;
esac