#!/usr/bin/env bash

set -e
# declare verbose debug output
declare -gx PS4=$'\E[0;10m\E[1m\033[1;31m\033[1;37m[\033[1;35m${BASH_SOURCE[0]##*/}:\033[1;34m${FUNCNAME[0]:-NOFUNC}():\033[1;33m${LINENO}\033[1;37m] - \033[1;33mDEBUG: \E[0;10m'

REPO_ROOT="${PWD}"
source "${REPO_ROOT}/build-scripts/stacktrace.sh"
set_colors
REPO="${REPO:-rhino-linux/os}"
BRANCH="main"
RUN_ID=""
OUT_DIR="."
SELECTED=()

# images generated by the deploy workflows, keyed by selector
# key is accepted as an argument then is pattern matched with the uploaded artifact name
declare -A PINE64_IMAGES=(
  [pinephone]="Rhino-Linux-*-pinephone.img.xz"
  [pinephone-lomiri]="Rhino-Linux-*-pinephone-lomiri.img.xz"
  [pinephonepro]="Rhino-Linux-*-pinephonepro.img.xz"
  [pinephonepro-lomiri]="Rhino-Linux-*-pinephonepro-lomiri.img.xz"
  [pinetab]="Rhino-Linux-*-pinetab.img.xz"
  [pinetab-lomiri]="Rhino-Linux-*-pinetab-lomiri.img.xz"
  [pinetab2]="Rhino-Linux-*-pinetab2.img.xz"
  [pinetab2-lomiri]="Rhino-Linux-*-pinetab2-lomiri.img.xz"
)

declare -A RPI_IMAGES=(
  [rpi-desktop]="Rhino-Linux-*-rpi-desktop.img.xz"
  [rpi-server]="Rhino-Linux-*-rpi-server.img.xz"
)

declare -A ISO_IMAGES=(
  [amd64]="Rhino-Linux-*-amd64.iso"
  [amd64-lomiri]="Rhino-Linux-*-amd64-lomiri.iso"
  [arm64]="Rhino-Linux-*-arm64.iso"
  [arm64-lomiri]="Rhino-Linux-*-arm64-lomiri.iso"
)

PINE64_WORKFLOW="build-pine64.yaml"
RPI_WORKFLOW="build-rpi.yaml"
ISO_WORKFLOW="build-iso.yaml"

function help_message() {
    echo -e "Usage: $0 [SELECTOR...] [OPTIONS]

Download images produced by the deploy workflows from GitHub Actions.

SELECTOR:
    Images to download (default: all):
    - all
    - pinephone, pinephone-lomiri
    - pinephonepro, pinephonepro-lomiri
    - pinetab, pinetab-lomiri
    - pinetab2, pinetab2-lomiri
    - rpi-desktop, rpi-server
    - amd64, amd64-lomiri
    - arm64, arm64-lomiri

OPTIONS:
    -h, --help          Show this help message
    -d, --dir DIR       Download into DIR (default: .)
    -b, --branch BRANCH Build branch to pull from (default: main)
    -r, --run ID        Download from a specific workflow run ID
    --repo OWNER/REPO   Repository to pull from (default: rhino-linux/os)"
}

function verify() {
    if ! command -v gh; then
        fancy_message error "The GitHub CLI (gh) is required"
        fancy_message error "Install it from https://github.com/cli/cli"
        exit 1
    fi
    if ! gh auth status; then
        fancy_message error "Not authenticated with gh, run 'gh auth login' first"
        exit 1
    fi
}

function parse_args() {
    while [[ $# -gt 0 ]]; do
        case "${1}" in
            -h|--help)
                help_message
                exit 0
            ;;
            -d|--dir)
                [[ -n ${2:-} ]] || { fancy_message error "$1 requires an argument"; exit 1; }
                OUT_DIR="${2}"
                shift 2
            ;;
            -b|--branch)
                [[ -n ${2:-} ]] || { fancy_message error "$1 requires an argument"; exit 1; }
                BRANCH="${2}"
                shift 2
            ;;
            -r|--run)
                [[ -n ${2:-} ]] || { fancy_message error "$1 requires an argument"; exit 1; }
                RUN_ID="${2}"
                shift 2
            ;;
            --repo)
                [[ -n ${2:-} ]] || { fancy_message error "$1 requires an argument"; exit 1; }
                REPO="${2}"
                shift 2
            ;;
            -*)
                fancy_message error "Unknown option: ${1}"
                help_message
                exit 1
            ;;
            *)
                SELECTED+=("${1}")
                shift
            ;;
        esac
    done

    local selector
    for selector in "${SELECTED[@]}"; do
        if [[ "${selector}" != "all" ]] \
            && ! [[ -n ${PINE64_IMAGES[${selector}]:-} ]] \
            && ! [[ -n ${RPI_IMAGES[${selector}]:-} ]] \
            && ! [[ -n ${ISO_IMAGES[${selector}]:-} ]]; then
            fancy_message error "Unknown image: ${selector}"
            help_message
            exit 1
        fi
    done
}

function in_selection() {
    local key="${1}" i
    [[ ${#SELECTED[@]} -eq 0 ]] && return 0
    for i in "${SELECTED[@]}"; do
        [[ "${i}" == "${key}" || "${i}" == "all" ]] && return 0
    done
    return 1
}

function find_run() {
    local workflow="${1}" run
    run="$(gh run list --repo "${REPO}" --workflow "${workflow}" \
        --branch "${BRANCH}" --status success --limit 1 \
        --json databaseId --jq '.[0].databaseId')"
    if [[ -z ${run} ]] || [[ "${run}" == "null" ]]; then
        fancy_message error "No successful ${workflow} run found for ${BRANCH}"
        exit 1
    fi
    echo "${run}"
}

function download() {
    local workflow="${1}" run="${2}" args=() key pattern
    for key in "${!PINE64_IMAGES[@]}" "${!RPI_IMAGES[@]}" "${!ISO_IMAGES[@]}"; do
        if [[ -n ${PINE64_IMAGES[${key}]:-} ]]; then
            [[ "${workflow}" == "${PINE64_WORKFLOW}" ]] || continue
            pattern="${PINE64_IMAGES[${key}]}"
        elif [[ -n ${RPI_IMAGES[${key}]:-} ]]; then
            [[ "${workflow}" == "${RPI_WORKFLOW}" ]] || continue
            pattern="${RPI_IMAGES[${key}]}"
        else
            [[ "${workflow}" == "${ISO_WORKFLOW}" ]] || continue
            pattern="${ISO_IMAGES[${key}]}"
        fi
        in_selection "${key}" || continue
        args+=("--pattern" "${pattern}")
    done
    [[ ${#args[@]} -gt 0 ]] || return
    fancy_message info "Downloading from ${workflow} run ${run}"
    gh run download "${run}" --repo "${REPO}" --dir "${OUT_DIR}" "${args[@]}"
}

function main() {
    parse_args "$@"
    verify
    mkdir -p "${OUT_DIR}"

    local pine64=false rpi=false iso=false run_pine64="" run_rpi="" run_iso="" key
    if [[ -n ${RUN_ID} ]]; then
        fancy_message warn "Using provided run ${RUN_ID} for every workflow"
        run_pine64="${RUN_ID}"
        run_rpi="${RUN_ID}"
        run_iso="${RUN_ID}"
    else
        for key in "${!PINE64_IMAGES[@]}"; do
            in_selection "${key}" && pine64=true
        done
        for key in "${!RPI_IMAGES[@]}"; do
            in_selection "${key}" && rpi=true
        done
        for key in "${!ISO_IMAGES[@]}"; do
            in_selection "${key}" && iso=true
        done
        ${pine64} && run_pine64="$(find_run "${PINE64_WORKFLOW}")"
        ${rpi} && run_rpi="$(find_run "${RPI_WORKFLOW}")"
        ${iso} && run_iso="$(find_run "${ISO_WORKFLOW}")"
    fi

    [[ -n ${run_pine64} ]] && download "${PINE64_WORKFLOW}" "${run_pine64}"
    [[ -n ${run_rpi} ]] && download "${RPI_WORKFLOW}" "${run_rpi}"
    [[ -n ${run_iso} ]] && download "${ISO_WORKFLOW}" "${run_iso}"

    fancy_message info "Images ready for upload under ${OUT_DIR}"
}

main "$@"
