#!/bin/bash
set -ex

kver=6.2.0-okpine-pro

libdir="/usr/lib/$DPKG_MAINTSCRIPT_PACKAGE/"
[ -d "$libdir" ] || exit 0

cd "$libdir"
mkdir -p /boot/dtb-$kver/
find -iname '*.dtb' -exec cp --parents {} /boot/dtb-$kver/ \;