#!/bin/bash
set -ex

kern="$DPKG_MAINTSCRIPT_PACKAGE"
kver=${kern/linux-image-/}

U_BOOT_PARAMETERS="console=ttyS0,115200n8 consoleblank=0 loglevel=7 rw splash plymouth.ignore-serial-consoles vt.global_cursor_default=0" \
/etc/kernel/postinst.d/zz-u-boot-menu "$kver"
