ARCH="arm64"
IMAGE_NAME="rpi4"
NAME="Rhino Linux"
MIRROR_PROFILE="ports"
PACKAGE_LISTS_SUFFIX="calamares"

HOST_ARCH="$(dpkg --print-architecture 2>/dev/null || uname -m)"
if [ "$HOST_ARCH" = amd64 ] || [ "$HOST_ARCH" = x86_64 ]; then
    QEMU_ARCH="arm64"
    QEMU_STATIC="/usr/bin/qemu-aarch64-static"
fi
