#!/bin/sh

BASECODENAME="devel"
BASEVERSION="devel"
CODENAME="devel"
RELEASE="1"
SUBVER=""
CHANNEL="all"
DISTRO_NAME="Rhino Linux"
OUTPUT_SUFFIX=""
PACKAGE_LISTS_SUFFIX=""
IMAGE_SUFFIX=""
BOOTLOADERS=""
QEMU_ARCH=""
QEMU_STATIC=""

TERRAFORM_CONFIG_DIRS="${TERRAFORM_CONFIG_DIRS:-etc/terraform.d}"
for config_dir in $TERRAFORM_CONFIG_DIRS; do
    for config in "$config_dir"/*.conf; do
        [ -f "$config" ] && . "$config"
    done
done

VERSION="$(date +%Y).$RELEASE"

case "$MIRROR_PROFILE" in
    generic)
        if [ "$ARCH" = arm64 ]; then
            MIRROR_URL="http://ports.ubuntu.com/ubuntu-ports/"
            SECURITY_URL="$MIRROR_URL"
            BOOTLOADERS="grub-efi"
        else
            MIRROR_URL="http://archive.ubuntu.com/ubuntu/"
            SECURITY_URL="http://security.ubuntu.com/ubuntu/"
            BOOTLOADERS="syslinux grub-efi"
        fi
        ;;
    ports)
        MIRROR_URL="http://ports.ubuntu.com/ubuntu-ports/"
        SECURITY_URL="$MIRROR_URL"
        ;;
esac

FNAME="Rhino-Linux-$VERSION$SUBVER-$IMAGE_NAME$IMAGE_SUFFIX"
