#!/bin/bash

if [[ -z "${terra_platform}" || -z "${terra_envir}" ]]; then
  echo "'terra_platform' or 'terra_envir' variable not set, exiting..."
  exit 1
fi

# values used by all platforms and environments {
# base codename
BASECODENAME="devel"
# base version
BASEVERSION="devel"
# distribution codename
CODENAME="devel"
# distribution version
RELEASE="1"
SUBVER=""
VERSION="$(date +%Y).${RELEASE}"
# distribution channel
#CHANNEL="unstable"
CHANNEL="all"
# distribution name
DISTRO_NAME="Rhino Linux"
# disk hostname
NAME="rhino-live"
# suffix for generated .iso files
OUTPUT_SUFFIX=""
# full image name
FNAME="Rhino-Linux-${VERSION}${SUBVER}-${terra_platform}"
if [[ ${terra_envir} == "lomiri" ]]; then
  FNAME="${FNAME}-lomiri"
fi
# } end of generic values

# platform and architecture selectors
# target architecture + output type
case "${terra_platform}" in
  amd64|arm64)
    ARCH="${terra_platform}"
    BUILD_TYPE="iso"
    BUILD_PLATFORM="iso"
    # folder suffix for the package lists to use
    PACKAGE_LISTS_SUFFIX="calamares"
    # bootloaders tweak
    if [[ ${ARCH} == "arm64" ]]; then
      BOOTLOADERS="grub-efi"
    else
      BOOTLOADERS="syslinux grub-efi"
    fi
  ;;
  *)
    ARCH="arm64"
    BUILD_TYPE="img"
    if [[ "${terra_platform}" == "rpi" ]]; then
      BUILD_PLATFORM="rpi"
    else
      BUILD_PLATFORM="pine64"
    fi
  ;;
esac

# mirrors to fetch packages from
if [[ ${ARCH} == "arm64" ]]; then
  MIRROR_URL="http://ports.ubuntu.com/ubuntu-ports/"
  SECURITY_URL="${MIRROR_URL}"
else
  MIRROR_URL="http://archive.ubuntu.com/ubuntu/"
  SECURITY_URL="http://security.ubuntu.com/ubuntu/"
fi

# set alternate QEMU if building for not-this-architecture
if [[ ${ARCH} == "arm64" && $(dpkg --print-architecture) == "amd64" ]]; then
  QEMU_ARCH="arm64"
  if [[ -x /usr/bin/qemu-aarch64-static ]]; then
    QEMU_STATIC="/usr/bin/qemu-aarch64-static"
  elif [[ -x /usr/bin/qemu-aarch64 ]]; then
    QEMU_STATIC="/usr/bin/qemu-aarch64"
  else
    echo "[\033[1;33m*\033[0m] \033[1mWARNING\033[0m: Building without ARM64 QEMU user emulator"
  fi
elif [[ ${ARCH} == "amd64" && $(dpkg --print-architecture) == "arm64" ]]; then
  QEMU_ARCH="amd64"
  if [[ -x /usr/bin/qemu-x86_64-static ]]; then
    QEMU_STATIC="/usr/bin/qemu-x86_64-static"
  elif [[ -x /usr/bin/qemu-x86_64 ]]; then
    QEMU_STATIC="/usr/bin/qemu-x86_64"
  else
    echo "[\033[1;33m*\033[0m] \033[1mWARNING\033[0m: Building without AMD64 QEMU user emulator"
  fi
fi
