name: Build PINE64 Images

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.platform }} ${{ matrix.environment }} rootfs
    strategy:
      fail-fast: false
      matrix:
        platform:
          - pinephone
          - pinetab
        environment:
          - unicorn
          - lomiri
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Build rootfs
        run: |
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          sudo rm -rf /var/lib/apt/lists/*
          sudo ./rhino-os.sh build \
            "${{ matrix.platform }}" \
            "${{ matrix.environment }}" \
            "build_${{ matrix.platform }}"

      - name: Upload rootfs
        uses: actions/upload-artifact@v7
        with:
          name: rootfs-${{ matrix.platform }}-${{ matrix.environment }}
          path: build_${{ matrix.platform }}/binary
          if-no-files-found: error
          retention-days: 1
          compression-level: 0

  deploy:
    name: Deploy ${{ matrix.target.rootfs }} ${{ matrix.environment }} image
    needs: build
    if: ${{ !cancelled() }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - platform: pinephone
            rootfs: pinephone
          - platform: pinephonepro
            rootfs: pinephone
          - platform: pinetab
            rootfs: pinetab
          - platform: pinetab2
            rootfs: pinetab
        environment:
          - unicorn
          - lomiri

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download rootfs
        uses: actions/download-artifact@v8
        with:
          name: rootfs-${{ matrix.target.rootfs }}-${{ matrix.environment }}
          path: build_${{ matrix.target.rootfs }}/binary

      - name: Deploy image
        run: |
          sudo ./rhino-os.sh deploy \
            "${{ matrix.target.platform }}" \
            "${{ matrix.environment }}" \
            "build_${{ matrix.target.rootfs }}"

      - name: Compress image
        run: |
          xz -T0 -v "build_${{ matrix.target.rootfs }}/builds/Rhino"*.img
          echo "IMGNAME=$(cd "build_${{ matrix.target.rootfs }}/builds"; ls *.img.xz)" >> $GITHUB_ENV

      - name: Upload image
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.IMGNAME }}
          path: build_${{ matrix.target.rootfs }}/builds/${{ env.IMGNAME }}
          if-no-files-found: error
          compression-level: 0
